//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlog.Model
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArticleInfo()
        {
            this.CommentInfo = new HashSet<CommentInfo>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string ArticleTitle { get; set; }
        public string ArticleContent { get; set; }
        public System.DateTime PubTime { get; set; }
        public int ReadCount { get; set; }
        public int ArticleTypeId { get; set; }
        public string FacePhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    	[JsonIgnore]
        public virtual ICollection<CommentInfo> CommentInfo { get; set; }
    	[JsonIgnore]
        public virtual ArticleType ArticleType { get; set; }
    	[JsonIgnore]
        public virtual UserInfo UserInfo { get; set; }
    }
}
